apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: demo-multi-step
spec:
  steps:
    - name: first
      image: quay.io/centos/centos:stream9
      command:
        - /bin/bash
        - -c
        - echo "First step"
    - name: second
      image: quay.io/centos/centos:stream9
      command:
        - /bin/bash
        - -c
        - echo "Second step"
