apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: pipeline-ordering-task
spec:
  params:
    - name: task-name
      type: string
    - name: time
      type: string
      default: ""
  steps:
    - name: first-task
      image: quay.io/centos/centos:stream9
      command:
        - /bin/bash
      args: ['-c', 'echo Ran to the first task $(params.task-name)']
    - name: second-task
      image: quay.io/centos/centos:stream9
      command:
        - /bin/bash
      args: ['-c', 'echo Ran to the second task $(params.time)']
    - name: logger
      image: quay.io/centos/centos:stream9
      command:
        - /bin/bash
      args: ['-c', 'echo Ran to the last task $(date +%d/%m/%Y %T) - Task $(params.task-name) Completed']
