- hosts: ntp-server
  tasks:
  - name: install chrony package
    dnf:
      name: chrony
      state: present    ## 실 서버에서는 latest 가급적이면 사용 금지.
  - name: copy chrony.conf file  ## grep -Ev '^#|^$' /etc/chrony.conf > chrony.conf
    copy:
      src: chrony.conf
      dest: /etc/chrony.conf
  - name: start chronyd.service
    systemd:
      name: chronyd
      state: restarted
      enabled: true

- hosts: ntp-client
  tasks:
  - name: install EPEL repository
    dnf:
      name: epel-release
      state: present
  - name: install systemd-timesyncd
    dnf:
      name: systemd-timesyncd
      state: present
  - name: copy timesyncd.conf to /etc/systemd/timesyncd.conf
    copy:
      src: timesyncd.conf
      dest: /etc/systemd/timesyncd.conf
  - name: start systemd-timesyncd.service
    systemd:
      name: systemd-timesyncd.service
      state: restarted
      enabled: true
  - name: stop chronyd.service
    systemd:
      name: chronyd
      state: stopped
      enabled: false
      masked: true
