- hosts: all

  tasks:
    - name: copy update-openssh.tar to remote node
      copy:
        src: files/update-openssh.tar
        dest: /tmp/update-openssh.tar
    - name: unarchive update-openssh.tar
      unarchive:
        src: /tmp/update-openssh.tar
        dest: /tmp/
    - name: copy update-openssh to the yum repository dir
      copy:
        src: files/update-openssh.repo
        dest: /etc/yum.repos.d/update-openssh.repo
    - name: update openssh package
      dnf:
        name: openssh
        state: latest
        disablerepo: "appstream,baseos"
        enablerepo: tmp_update-openssh
