apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: demo-pipeline-dice-pipeline 
spec:
  tasks:
  - name: message
    taskRef:
      name: welcome-message
  - name: roll
    taskRef:
      name: demo-pipeline-dice-task
