apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: demo-pipeline-dice-task-param-result
spec:
  params:
  - name: sideNum
    description: number of sides to the dice
    default: 6
    type: string
  results:
  - name: dice-result
    description: result of dice roll number
  steps:
  - name: rolling-n-rolling-dice
    image: quay.io/centos/centos:stream9
    script: |
      dnf install php-cli -y
      php -r 'echo rand(1,$(params.sideNum));' > dice-result.txt
