apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: demo-pipeline-dice-pipeline-result
spec:
  params:
  - name: sideNum
    type: string
    default: 6
  tasks:
  - name: first
    params:
    - name: text
      value: "The dice sides is $(params.sideNum)"
    taskRef:
      name: logger

  - name: roll
    params:
    - name: sides
      value: "$(params.sideNum)"
    taskRef:
      name: demo-pipeline-dice-task-param-result
    runAfter:
    - first
