apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: demo-pipeline-dice-pipeline3
spec:
  params:
  - name: sidenum
    type: string
    default: 6
    description: number of sides the dice
  tasks:
  - name: first
    taskRef:
      name: hello
  - name: roll
    params:
    - name: sides
      value: "$(params.sidenum)"
    taskRef:
      name: demo-pipeline-dice-task
