apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: demo-workspace-clone-github
spec:
  params:
    - name: repo
      type: string
      description: Git Repository clone from github
      default: https://github.com/tangt64/duststack-osp-auto
  workspaces:
    - name: source
  steps:
    - name: clone
      image: quay.io/centos/centos:stream9
      workingDir: $(workspaces.source.path)
      script: |
        dnf install git -y 
        git clone -v $(params.repo) $(workspaces.source.path)
    - name: list
      image: quay.io/centos/centos:stream9
      workingDir: $(workspaces.source.path)
      script: |
        ls -l $(workspaces.source.path)
    - name: ansible
      image: quay.io/centos/centos:stream9
      workingDir: $(workspaces.source.path)/duststack-osp-auto
      script: |
        dnf install ansible -y
        ansible-playbook --syntax-check playbooks/osp-install.yaml
