apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: demo-pipeline-reuse-task
spec:
  params:
  - name: text
    type: string
  steps:
  - name: log
    image: quay.io/centos/centos:stream9
    script: |
      DATE=$(date +%d/%m/%Y\ %T)
      echo [$DATE] - $(params.text)
