apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: demo-task-param
spec:
  params:
  - name: username
    type: string
  steps:
  - image: quay.io/centos/centos:stream9
    command:
      - /bin/bash
      - -c
      - echo "Hello $(params.username)"
  steps:
  - image: quay.io/centos/centos
    command:
      - /bin/bash
      - -c
      - echo "Hello $(params.username)"

