apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: demo-task-param-default
spec:
  params:
  - name: users
    type: array
    default:
    - test1
    - test2
    - test3
  steps:
  - name: list-users
    image: quay.io/centos/centos:stream9
    args:
    - $(params.users[*])
    command:
    - /bin/bash
    - -c
    - for ((i=0;i<=$#;i++)); do echo "$#" "$i" "${!i}"; done
