apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: exit-debug-pipeline
spec:
  tasks:
  - name: clone
    taskRef:
      name: log-and-exit
    params:
      - name: text
        value: "Simulating git clone"
      - name: exitcode
        value: "0"
  - name: unit-tests
    taskRef:
      name: exit-debug-task
    params:
      - name: text
        value: "Simulating unit testing"
      - name: exitcode
        value: "0"
    runAfter:
      - clone
  - name: deploy
    taskRef:
      name: exit-debug-task
    params:
      - name: text
        value: "Simulating deployment"
      - name: exitcode
        value: "0"
    runAfter:
      - unit-tests
  finally:
    - name: cleanup-task
      taskRef:
        name: task-cleanup
