apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-ordering-pipeline
spec:
  tasks:
  - name: first
    params:
      - name: task-name
        value: A
      - name: time
        value: "2PM"
    taskRef:
      name: first-task
  - name: second
    params:
      - name: task-name
        value: B
    taskRef:
      name: first-task
  - name: third
    params:
      - name: task-name
        value: C
      - name: time
        value: "3PM"
    taskRef:
      name: second-task
  - name: fourth
    params:
      - name: text
        value: "This is Fourth"
    taskRef:
      name: logger
