# git clone https://github.com/Yggdroot/indentLine.git ~/.vim/pack/vendor/start/indentLine
# vim -u NONE -c "helptags  ~/.vim/pack/vendor/start/indentLine/doc" -c "q"


#  ~/.config/yamllint/config 
#
# extends: relaxed
#
# rules:
#  line-length: disable

autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab

set foldlevelstart=20

let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
let g:ale_sign_error = '✘'
let g:ale_sign_warning = '⚠'
let g:ale_lint_on_text_changed = 'never'