---
- hosts: all

  become: false
  remote_user: student

  vars:
    iamokay: true

  tasks:
  - shell: cat /etc/hostname
    register: result_shell

  - debug:
      msg: "{{ result_shell.rc }}"        ### return count: 0

  - debug:
      msg: "the shell is okay"
    when: result_shell.rc|bool

  - debug:
      msg: "the shell return value is '{{ result_shell.stdout }}'"
