AWSTemplateFormatVersion: '2010-09-09'
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 172.16.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true

  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 172.16.0.0/24
      AvailabilityZone: ap-northeast-2a

  ApplicationSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: For Sample Internal Application
      VpcId: !Ref VPC

  ApplicationInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0ee82191e264e07cc
      InstanceType: t2.micro
      KeyName: mykeypair
      SubnetId: !Ref PrivateSubnet
      SecurityGroupIds: 
        - !Ref ApplicationSecurityGroup

  mykeypair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: mykeypair