set ts=2
set sts=2
set sw=2
set expandtab
set number

let g:indentLine_char = '⦙'

syntax on
filetype indent plugin on
set ruler
set cursorcolumn
set foldlevelstart=20

let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
let g:ale_sign_error = '✘'
let g:ale_sign_warning = '⚠'
let g:ale_lint_on_text_changed = 'never'
